 platform :ios, '9.0'

target '网易新闻' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 网易新闻
 pod 'AFNetworking', '~> 3.1.0'

end
